### ISSUE TITLE
Error ocurring when adding new user

### ISSUE THREAD

**Issue by maximilianeder** [sthorsten/CasterDashboard2#23]
Pulled the project from docker and ran it unchanged. After logging into the admin backend with the default credential I clicked on "+Users" and added a name plus password. Clicking any of the "Save" Buttons causes a code 500 Internal Error with the following stacktrace:

```
casterdashboard-backend-1   | 2022-03-26 02:48:46,799 INFO     New user. Creating additional data...
casterdashboard-backend-1   | 2022-03-26 02:48:47,292 ERROR    Exception inside application: errors/error500.html
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-nginx-1     | 172.18.0.1 - - [26/Mar/2022:01:48:47 +0000] "POST /admin/auth/user/add/ HTTP/1.1" 500 465 "http://127.0.0.1/admin/auth/user/add/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0" "-"
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
casterdashboard-backend-1   |     response = await wrapped_callback(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 683, in wrapper
casterdashboard-backend-1   |     return self.admin_site.admin_view(view)(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
casterdashboard-backend-1   |     response = view_func(request, *args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
casterdashboard-backend-1   |     response = view_func(request, *args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
casterdashboard-backend-1   |     return view(request, *args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
casterdashboard-backend-1   |     return bound_method(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
casterdashboard-backend-1   |     return view(request, *args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
casterdashboard-backend-1   |     return bound_method(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
casterdashboard-backend-1   |     response = view_func(request, *args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/auth/admin.py", line 119, in add_view
casterdashboard-backend-1   |     return self._add_view(request, form_url, extra_context)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/auth/admin.py", line 147, in _add_view
casterdashboard-backend-1   |     return super().add_view(request, form_url, extra_context)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1885, in add_view
casterdashboard-backend-1   |     return self.changeform_view(request, None, form_url, extra_context)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
casterdashboard-backend-1   |     return bound_method(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
casterdashboard-backend-1   |     response = view_func(request, *args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1745, in changeform_view
casterdashboard-backend-1   |     return self._changeform_view(request, object_id, form_url, extra_context)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1797, in _changeform_view
casterdashboard-backend-1   |     self.save_model(request, new_object, form, not add)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1220, in save_model
casterdashboard-backend-1   |     obj.save()
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 68, in save
casterdashboard-backend-1   |     super().save(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
casterdashboard-backend-1   |     self.save_base(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 872, in save_base
casterdashboard-backend-1   |     post_save.send(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
casterdashboard-backend-1   |     return [
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
casterdashboard-backend-1   |     (receiver, receiver(signal=self, sender=sender, **named))
casterdashboard-backend-1   |   File "/backend/src/./user/receivers.py", line 25, in new_user_post_save
casterdashboard-backend-1   |     Profile.objects.create(
casterdashboard-backend-1   | NameError: name 'Profile' is not defined
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
casterdashboard-backend-1   |     response = await get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 150, in __acall__
casterdashboard-backend-1   |     response = response or await self.get_response(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
casterdashboard-backend-1   |
casterdashboard-backend-1   | During handling of the above exception, another exception occurred:
casterdashboard-backend-1   |
casterdashboard-backend-1   | Traceback (most recent call last):
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
casterdashboard-backend-1   |     return await application(scope, receive, send)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/asgi.py", line 155, in __call__
casterdashboard-backend-1   |     await self.handle(scope, receive, send)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/asgi.py", line 177, in handle
casterdashboard-backend-1   |     response = await self.get_response_async(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 162, in get_response_async
casterdashboard-backend-1   |     response = await self._middleware_chain(request)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 44, in inner
casterdashboard-backend-1   |     response = await sync_to_async(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
casterdashboard-backend-1   |     ret = await asyncio.wait_for(future, timeout=None)
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
casterdashboard-backend-1   |     return await fut
casterdashboard-backend-1   |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
casterdashboard-backend-1   |     result = self.fn(*self.args, **self.kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 453, in thread_handler
casterdashboard-backend-1   |     return func(*args, **kwargs)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
casterdashboard-backend-1   |     response = handle_uncaught_exception(
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
casterdashboard-backend-1   |     return callback(request)
casterdashboard-backend-1   |   File "/backend/src/./dashboard/views.py", line 6, in error_500
casterdashboard-backend-1   |     return render(request, "errors/error500.html", status=500)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
casterdashboard-backend-1   |     content = loader.render_to_string(template_name, context, request, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
casterdashboard-backend-1   |     template = get_template(template_name, using=using)
casterdashboard-backend-1   |   File "/backend/.venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
casterdashboard-backend-1   |     raise TemplateDoesNotExist(template_name, chain=chain)
casterdashboard-backend-1   | django.template.exceptions.TemplateDoesNotExist: errors/error500.html
```

**Comment by sthorsten** [comment]
Seems like that this is a bug with running some hooks when creating a new user. That is probably an easy fix, I will look into it later today.
